version: '3.9'

services:

  pg:
    container_name: pg
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres_network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${POSTGRES_USER}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres_network

  minio:
    container_name: minio
    image: minio/minio
    command: server --console-address ":9001" /minio_data/
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ACCESS_KEY: ${AWS_ACCESS_KEY_ID}
      MINIO_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - minio_network
    volumes:
      - minio_data:/minio_data/

  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: mlflow
    depends_on: [ pg, minio ]
#    restart: always
    ports:
      - "5000:5000"
    networks:
      - postgres_network
      - minio_network
      - mlflow_network
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    command:
      pip install psycopg2 &&
      mlflow server
      --backend-store-uri
      postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      --default-artifact-root
      s3://${AWS_S3_BUCKET}/ --host 0.0.0.0

  fastapi_app:
    build: ..
    ports:
      - "80:8080"
    depends_on: [ mlflow ]
    networks:
      minio_network:
      mlflow_network:

volumes:
  postgres_data:
  pgadmin_data:
  minio_data:

networks:
  postgres_network:
    driver: bridge
  minio_network:
    driver: bridge
  mlflow_network:
    driver: bridge