[tool.black]
line-length = 80
skip-string-normalization = true

[flake8]
ignore = 'E203'
max-line-length = 80

[tool.pylint]
disable='C0103, C0114, C0116, C0115, W0707, E1120, R0913, R0801, R0902, E1101'
max-line-length=80

[tool.isort]
profile = "black"