name: CI pipeline

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e "./src[dev]"
      - name: Run flake8
        run: |
          flake8 src --append-config ./src/pyproject.toml

      - name: Run pylint
        run: |
          pylint src --fail-under=0.1 --rcfile=src/pyproject.toml $(git ls-files '*.py')

      - name: Run pytest
        run: pytest tests/

      - name: Run Black
        run: black --check src
