name: CI pipeline

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e "./src[dev]"

      - name: Run pylint
        run: |
          pylint src --fail-under=0 --rcfile=src/pyproject.toml $(git ls-files '*.py')

      - name: Run Black
        run: black --check --config src/pyproject.toml src/

      - name: Run isort
        run: isort src --check-only --settings-path src/pyproject.toml

      - name: Run pytest
        run: pytest tests/
